version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    command: python3 -m flask run -h 0.0.0.0 -p 8000
